# Generated by Django 4.1.7 on 2023-03-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=12)),
                ('des', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
